name: DOWNLOAD GAMES + COMMIT & PUSH

on: 
  workflow_dispatch:
  schedule:
    - cron: '0 0 1 * *' # This runs at midnight on the 1st day of every month

jobs:
  build: 
    runs-on: ubuntu-latest

    steps: 
    - name: Checkout Code 
      uses: actions/checkout@v2

    - name: Calculate Previous Month and Year
      id: calculate
      run: | 
        # Calculate previous month and year
        CURRENT_MONTH=$(date "+%-m")
        PREV_MONTH=$(printf "%02d" "$((CURRENT_MONTH - 1))")  
        PREV_YEAR=$(date "+%-Y")

        if [ $PREV_MONTH -eq 0 ]; then 
          PREV_MONTH=12
          PREV_YEAR=$((PREV_YEAR - 1))
        fi 

        echo "month=$PREV_MONTH" >> $GITHUB_OUTPUT
        echo "year=$PREV_YEAR" >> $GITHUB_OUTPUT
    
    # - name: Run Download Games Script 
    #   run: |
    #     # Set Permission to run the script
    #     chmod +x download_games.sh
    #     # Download the games played in the previous month using previous month and previous year as arguments
    #     ./download_games.sh "${{ secrets.USERNAME }}" "${{ steps.calculate.outputs.month}}" "${{ steps.calculate.outputs.year}}"
    #   working-directory: ${{ github.workspace }}

    - name: Run Python Script to save games
      id: run_python
      run : |
        # Set Permission to run the file
        chmod +x download_games.py
        
        #Install python dependencies
        pip install -r games_requirements.txt.txt
        
        # Run the python script to  save the games
        TOTAL_GAMES=$(echo "$(python ./download_games.py '${{ secrets.USERNAME }}' '${{ steps.calculate.outputs.month}}' '${{ steps.calculate.outputs.year}}')" | grep -oE '[0-9]+' | tail -n1 )

        #get the $TOTAL_GAMES value and store it in GITHUB_OUTPUT.
        echo "total_games=$TOTAL_GAMES" >> $GITHUB_OUTPUT

      working-directory: ${{ github.workspace }}

    - name: Commit and Push Changes
      run: |
        # Configure Git with your information
        git config --global user.email "${{ secrets.EMAIL }}"
        git config --global user.name "Parth"

        # Add all changes
        git add .

        # Commit with message
        git commit -m "Added Games played on chess.com in the last month"

        #push the code 
        git push origin master
      working-directory: ${{ github.workspace }}

    - name: whatsapp-notify
      if: always() # This setup with allways run, even if previous steps failed
      env:
        account_sid: ${{ secrets.ACCOUNT_SID }}
        auth_token: ${{ secrets.AUTH_TOKEN }}
        to_whatsapp_no: ${{ secrets.TO_NUMBER }}
        message: | 
          For ${{ secrets.USERNAME }}, ${{ steps.run_python.outputs.total_games }} have been added for ${{ steps.calculate.outputs.month}}/${{ steps.calculate.outputs.year}}; Job Status: ${{ job.status }}"
      run: |
        # Set Permission to run the file
        chmod +x download_games.py
        
        #Install python dependencies
        pip install -r message_requirements.txt.txt

        #Run the script to send the message 
        python ./send_message.py


      
