name: DOWNLOAD GAMES + COMMIT & PUSH

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 1 * *" # This runs at midnight on the 1st day of every month

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Run Python Script to save games
        id: run_python
        env:
          FROM_EMAIL: ${{ secrets.FROM_EMAIL }}
          APP_PASSWORD: ${{ secrets.APP_PASSWORD }}
          TO_EMAIL: ${{ secrets.TO_EMAIL }}
          LICHESS_TOKEN: ${{ secrets.LICHESS_TOKEN }}
          # Pass in users from repository vaiables
          CHESS_USERS: ${{ vars.CHESS_USERS }}
        run: |
          # Set Permission to run the file
          chmod +x main.py

          # Create venv
          python3 -m venv venv

          # Activate venv
          source venv/bin/activate

          # Install Dependencies
          pip install -r requirements.txt

          # Run the python script to  save the games
          python main.py

        working-directory: ${{ github.workspace }}

      # - name: Commit and Push Changes
      #   run: |
      #     # Configure Git with your information
      #     git config --global user.email "${{ secrets.EMAIL }}"
      #     git config --global user.name "GH Action - Parth Patel"

      #     # Add all changes
      #     git add .

      #     # Commit with message
      #     git commit -m "Added Games played on chess.com in the last month" || true

      #     #push the code 
      #     git push origin master || true
      #   working-directory: ${{ github.workspace }}
