name: UPLOAD CHESS GAMES TO GOOGLE DRIVE

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 1 * *" # This runs at midnight on the 1st day of every month

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

      - name: Calculate Previous Month and Year
        id: calculate
        run: |
          CURRENT_MONTH=$(date "+%-m")
          PREV_MONTH=$(printf "%02d" "$((CURRENT_MONTH - 1))")
          PREV_YEAR=$(date "+%-Y")
          if [ $PREV_MONTH -eq 0 ]; then 
            PREV_MONTH=12
            PREV_YEAR=$((PREV_YEAR - 1))
          fi 
          echo "month=$PREV_MONTH" >> $GITHUB_OUTPUT
          echo "year=$PREV_YEAR" >> $GITHUB_OUTPUT

      - name: Run Python Script to save games
        env:
          FROM_EMAIL: ${{ secrets.FROM_EMAIL }}
          APP_PASSWORD: ${{ secrets.APP_PASSWORD }}
          TO_EMAIL: ${{ secrets.TO_EMAIL }}
          LICHESS_TOKEN: ${{ secrets.LICHESS_TOKEN }}
          GCP_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
          CHESS_USERS: ${{ vars.CHESS_USERS }}
        run: |
          source venv/bin/activate
          python main.py "${{ steps.calculate.outputs.month}}" ${{ steps.calculate.outputs.year}}
        working-directory: ${{ github.workspace }}
